[workspace]
members = ["days/day01", "days/day02", "days/day03", "days/day04", "days/day05", "days/day06", "days/day07"]
resolver = "2"

[workspace.dependencies]
parameterized = "2.0.0"
common = { path = "common"}
